[versions]
agp = "8.4.2"
kotlin = "1.9.24"
scala = "2.11.12"

[libraries]
scala-library = { module = "org.scala-lang:scala-library", version.ref = "scala" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
